/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListProduct200Response,
} from '../models/index';
import {
    ListProduct200ResponseFromJSON,
    ListProduct200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get a list of products
     */
    async listProductRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProduct200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProduct200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of products
     */
    async listProduct(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProduct200Response> {
        const response = await this.listProductRaw(initOverrides);
        return await response.value();
    }

}
